### ISSUE TITLE
`@local_jdk` errors when querying dependencies of the tutorial

### ISSUE THREAD

**Issue by Infinisil** [tweag/rules_haskell#1414]
**Describe the bug**
Executing the `bazel query` command for the `//main:demorgan` target as suggested by the tutorial fails with
```
$ bazel query --nohost_deps --noimplicit_deps 'deps(//main:demorgan)' --output graph
ERROR: /home/infinisil/.cache/bazel/_bazel_infinisil/84c287ee26510af98721d201b157fe7c/external/local_jdk/BUILD.bazel:210:10: Label '@local_jdk//:lib/tools.jar' is invalid because '@local_jdk//lib' is a subpackage; perhaps you meant to put the colon here: '@local_jdk//lib:tools.jar'?
ERROR: /home/infinisil/.cache/bazel/_bazel_infinisil/84c287ee26510af98721d201b157fe7c/external/local_jdk/BUILD.bazel:133:10: Target '@local_jdk//:windows' contains an error and its package is in error and referenced by '@local_jdk//:jre-bin'
ERROR: /home/infinisil/.cache/bazel/_bazel_infinisil/84c287ee26510af98721d201b157fe7c/external/local_jdk/BUILD.bazel:165:10: Target '@local_jdk//:jre-lib' contains an error and its package is in error and referenced by '@local_jdk//:jre-default'
ERROR: /home/infinisil/.cache/bazel/_bazel_infinisil/84c287ee26510af98721d201b157fe7c/external/local_jdk/BUILD.bazel:165:10: Target '@local_jdk//:jre-bin' contains an error and its package is in error and referenced by '@local_jdk//:jre-default'
ERROR: /home/infinisil/.cache/bazel/_bazel_infinisil/84c287ee26510af98721d201b157fe7c/external/local_jdk/BUILD.bazel:200:13: Target '@local_jdk//:jdk-lib' contains an error and its package is in error and referenced by '@local_jdk//:jdk'
ERROR: /home/infinisil/.cache/bazel/_bazel_infinisil/84c287ee26510af98721d201b157fe7c/external/local_jdk/BUILD.bazel:200:13: Target '@local_jdk//:jdk-include' contains an error and its package is in error and referenced by '@local_jdk//:jdk'
ERROR: /home/infinisil/.cache/bazel/_bazel_infinisil/84c287ee26510af98721d201b157fe7c/external/local_jdk/BUILD.bazel:200:13: Target '@local_jdk//:jre-default' contains an error and its package is in error and referenced by '@local_jdk//:jdk'
ERROR: /home/infinisil/.cache/bazel/_bazel_infinisil/84c287ee26510af98721d201b157fe7c/external/local_jdk/BUILD.bazel:200:13: Target '@local_jdk//:jdk-bin' contains an error and its package is in error and referenced by '@local_jdk//:jdk'
ERROR: /home/infinisil/.cache/bazel/_bazel_infinisil/84c287ee26510af98721d201b157fe7c/external/bazel_tools/tools/jdk/BUILD:336:6: Target '@local_jdk//:jdk' contains an error and its package is in error and referenced by '@bazel_tools//tools/jdk:jdk'
ERROR: Evaluation of query "deps(//main:demorgan)" failed due to BUILD file errors
Loading: 0 packages loaded
```

**To Reproduce**
1. `nix-shell` in the repository root
2. Add the suggested arguments to `.bazelrc.local`
3. `cd tutorial`
4. `bazel query --nohost_deps --noimplicit_deps 'deps(//main:demorgan)' --output graph`

**Expected behavior**
The dependency graph should be output

**Environment**
 - OS name + version: NixOS 20.09
 - Bazel version: 3.3.1
 - Version of the rules: master (aabeedc18f5e5db030ca1aa0c10a7dc14e4a4a55)

**Comment by Profpatsch** [comment]
According to https://github.com/NixOS/nixpkgs/pull/98611 (which you linked), you need to use `cquery`, because `query` will not take into account any toolchain-related ifdefs.

**Comment by mboes** [comment]
@Infinisil I just ran into this error as well, though just with a `bazel build //...` - not even trying to `query`. I fixed it with `bazel build clean --expunge`. It appears that the reason this works is that changes Bazel itself in Nixpkgs don't get noticed by Bazel, so purging the Bazel cache is necessary.

**Comment by teto** [comment]
I just ran into this as well with a simple `bazel build //...`  (bazel 3.3.1). `bazel clean --expunge` didn't fix it, nor a `rm -rf ~/.cache/bazel*`. I fetch bazel from nixpkgs a322b32e9d74fb476944ff6cfb55833dc69cfaaa (19 november).

**Comment by mboes** [comment]
@teto are you using a disk cache / remote cache?

**Comment by teto** [comment]
indeed, it works when disabling the cache ( ` build --remote_cache= build --disk_cache=~/.cache/bazel_disk_cache_for_debug`). We use exactly the same bazel/nixpkgs version in another project (both share the same remote cache) without seeing this issue.

**Comment by mboes** [comment]
You said different project? Maybe the different project has different objects in the remote cache and so might not be affected by this cache poisoning issue. The poisoning itself looks like it's a Bazel issue, not a rules_haskell one. Indeed the `@local_jdk` external repo is an internal one created by Bazel, not rules_haskell. It might be that it only happens when you apply new patches to Bazel without changing its version number. Or it might be that Bazel unwisely omits to invalidate the cache when you change the version. But I see no evidence so far that this is a rules_haskell issue. Either a Bazel issue or specifically a Bazel-from-Nixpkgs issue. Worth filing this upstream and then I think we can close this issue.

**Comment by teto** [comment]
as a first move I will try to upgrade our bazel version once that Pr is fixed https://github.com/NixOS/nixpkgs/pull/105439
