### ISSUE TITLE
Debug builds error and log "undefined reference" messages

### ISSUE THREAD

**Issue by palmerlao** [tweag/rules_haskell#400]
When using `bazel build -c dbg ...` on a work project, I get errors similar to the following:

```
ERROR: /home/palmer/.cache/bazel/_bazel_palmer/9ef7fb33c244ac0b713bdee31c7518e3/external/haskell_happy/BUILD:17:1: error executing shell command: '${1+"$@"} $(< bazel-out/k8-dbg/bin/external/haskell_happy/_obj_prof/happy_bin.manifest)' failed (Exit 1)
bazel-out/k8-dbg/bin/external/haskell_mtl/libHSexternalZShaskellZUmtlZSmtl-2.2.2_p.a(Class.p_o):/tmp/ghc2_4/ghc_52.p_o:s5Aw_info: error: undefined reference to 'transformerszm0zi5zi2zi0_ControlziMonadziTransziRWSziLazzy_reader_closure'
bazel-out/k8-dbg/bin/external/haskell_mtl/libHSexternalZShaskellZUmtlZSmtl-2.2.2_p.a(Class.p_o):/tmp/ghc2_4/ghc_52.p_o:s5Av_info: error: undefined reference to 'transformerszm0zi5zi2zi0_ControlziMonadziTransziRWSziLazzy_ask_closure'
bazel-out/k8-dbg/bin/external/haskell_mtl/libHSexternalZShaskellZUmtlZSmtl-2.2.2_p.a(Class.p_o):/tmp/ghc2_4/ghc_52.p_o:s5Au_info: error: undefined reference to 'transformerszm0zi5zi2zi0_ControlziMonadziTransziRWSziLazzy_zdfMonadRWST_closure'
bazel-out/k8-dbg/bin/external/haskell_mtl/libHSexternalZShaskellZUmtlZSmtl-2.2.2_p.a(Class.p_o):ghc_48.c:externalZZShaskellZZUmtlZZSmtlzm2zi2zi2_ControlziMonadziReaderziClass_zdfMonadReaderrRWST0_info: error: undefined reference to 'transformerszm0zi5zi2zi0_ControlziMonadziTransziRWSziLazzy_local_closure'
bazel-out/k8-dbg/bin/external/haskell_happy/libHSexternalZShaskellZUhappyZSPaths-happy-1.0.0_p.a(Paths_happy.p_o):/tmp/ghc2_0/ghc_7.p_o:s1em_info: error: undefined reference to 'filepathzm1zi4zi1zi2_SystemziFilePathziPosix_takeDirectory_closure'
bazel-out/k8-dbg/bin/external/haskell_happy/libHSexternalZShaskellZUhappyZSPaths-happy-1.0.0_p.a(Paths_happy.p_o):/tmp/ghc2_0/ghc_7.p_o:s1eo_info: error: undefined reference to 'filepathzm1zi4zi1zi2_SystemziFilePathziPosix_zlzszg_closure'
bazel-out/k8-dbg/bin/external/haskell_happy/libHSexternalZShaskellZUhappyZSPaths-happy-1.0.0_p.a(Paths_happy.p_o):/tmp/ghc2_0/ghc_7.p_o:s1es_info: error: undefined reference to 'filepathzm1zi4zi1zi2_SystemziFilePathziPosix_zlzszg_closure'
bazel-out/k8-dbg/bin/external/haskell_happy/libHSexternalZShaskellZUhappyZSPaths-happy-1.0.0_p.a(Paths_happy.p_o)(.data.rel.ro+0x18): error: undefined reference to 'filepathzm1zi4zi1zi2_SystemziFilePathziPosix_takeDirectory_closure'
bazel-out/k8-dbg/bin/external/haskell_happy/libHSexternalZShaskellZUhappyZSPaths-happy-1.0.0_p.a(Paths_happy.p_o)(.data.rel.ro+0x20): error: undefined reference to 'filepathzm1zi4zi1zi2_SystemziFilePathziPosix_zlzszg_closure'
```

Here are some snippets from our top-level `WORKSPACE` file that I hope are relevant:
```
github_http_archive(
    name = "io_tweag_rules_nixpkgs",
    project = "rules_nixpkgs",
    sha = "896c2d96a70a408c545cc491974068c36f507009",
    user = "tweag",
)

load("@io_tweag_rules_nixpkgs//nixpkgs:nixpkgs.bzl", "nixpkgs_git_repository", "nixpkgs_package")

nixpkgs_git_repository(
    name = "nixpkgs",
    revision = "ee80654b5267b07ba10d62d143f211e0be81549e",
)

github_http_archive(
    name = "io_tweag_rules_haskell",
    project = "rules_haskell",
    sha = "ade857db291fdc3cffc4435b73af27dd06aa48c4",
    user = "tweag",
)

load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

github_http_archive(
    name = "ai_formation_hazel",
    project = "hazel",
    sha = "296b60ef3cfd768061f541dbe49f8520f25bdbc8",
    user = "FormationAI",
)
```

I tried plodding along with minimizing our work monorepo into a smaller project that displays this issue, but don't know Bazel and friends well enough to do it very quickly. If that's highly useful, I can try continuing down that path.

**Comment by mboes** [comment]
It's *possible* that this is the same issue as #395. But without a minimal repro hard to confirm. Do you have two packages with targets that have the same name? Simple fix at #403.

**Comment by mboes** [comment]
#403 merged. Can you confirm whether this is a fix?

**Comment by iphydf** [comment]
I have a similar issue with `-c dbg`, possibly the same. The current master has this issue as well. I can't test/repro much until #394 is done. Once that's completed and merged, I'll make a repro.

**Comment by palmerlao** [comment]
I was not able to confirm that this fixed it for me. I tried upgrading our version of `rules_haskell` (see first line) and ran into some other errors that may not be related to this issue at all.
```
INFO: SHA256 (https://github.com/tweag/rules_haskell/archive/ea52da0835a1ce28a8d7c141dcb7e3ef936fa54b.tar.gz) = 84038d6f115995121c01c360c806c0356380139ae881425aaef1627bdf7550f8
/nix/store/gqg2vrcq7krqi9rrl6pphvsg81sb8pjw-gcc-wrapper-7.3.0
/nix/store/cmxaqb5cbzy4jk26na842n6hy1s4yn19-binutils-wrapper-2.28.1
INFO: Build options have changed, discarding analysis cache.
/nix/store/mmhdqindrpvg91a2vnrr76vxcn5a4n0x-ghc-8.2.2
ERROR: /home/palmer/.cache/bazel/_bazel_palmer/9ef7fb33c244ac0b713bdee31c7518e3/external/haskell_doctest/BUILD:17:1: every rule of type haskell_binary implicitly depends upon the target '@io_tweag_rules_haskell//haskell:assets/ghci_script', but this target could not be found because of: error loading package '@io_tweag_rules_haskell//haskell': Extension file not found. Unable to load package for '@io_bazel_skydoc//skylark:skylark.bzl': The repository could not be resolved
ERROR: /home/palmer/.cache/bazel/_bazel_palmer/9ef7fb33c244ac0b713bdee31c7518e3/external/haskell_doctest/BUILD:17:1: every rule of type haskell_binary implicitly depends upon the target '@io_tweag_rules_haskell//haskell:private/ghci_repl_wrapper.sh', but this target could not be found because of: error loading package '@io_tweag_rules_haskell//haskell': Extension file not found. Unable to load package for '@io_bazel_skydoc//skylark:skylark.bzl': The repository could not be resolved
ERROR: /home/palmer/.cache/bazel/_bazel_palmer/9ef7fb33c244ac0b713bdee31c7518e3/external/haskell_doctest/BUILD:17:1: every rule of type haskell_binary implicitly depends upon the target '@io_tweag_rules_haskell//haskell:ls_modules', but this target could not be found because of: error loading package '@io_tweag_rules_haskell//haskell': Extension file not found. Unable to load package for '@io_bazel_skydoc//skylark:skylark.bzl': The repository could not be resolved
ERROR: /home/palmer/.cache/bazel/_bazel_palmer/9ef7fb33c244ac0b713bdee31c7518e3/external/haskell_doctest/BUILD:17:1: every rule of type haskell_binary implicitly depends upon the target '@io_tweag_rules_haskell//haskell:dummy_static_lib', but this target could not be found because of: error loading package '@io_tweag_rules_haskell//haskell': Extension file not found. Unable to load package for '@io_bazel_skydoc//skylark:skylark.bzl': The repository could not be resolved
ERROR: Analysis of target '//:doctest-toolchain-impl' failed; build aborted: error loading package '@io_tweag_rules_haskell//haskell': Extension file not found. Unable to load package for '@io_bazel_skydoc//skylark:skylark.bzl': The repository could not be resolved
```

**Comment by iphydf** [comment]
Fwiw, I fixed that skydoc issue myself when testing and the undefined references still happened.

**Comment by mboes** [comment]
We'll need a minimal repro in that case.

**Comment by iphydf** [comment]
https://travis-ci.org/iphydf/repro400/jobs/421065933#L787
https://github.com/iphydf/repro400

I'll see about minimising it a bit more.

**Comment by palmerlao** [comment]
FWIW I got some slightly different errors with #419 :
```
ghc-iserv-prof: /home/palmer/.cache/bazel/_bazel_palmer/9ef7fb33c244ac0b713bdee31c7518e3/execroot/work_project/bazel-out/k8-dbg/bin/external/haskell_text/libHSexternalZShaskellZUtextZStext_p.a: unknown symbol `_hs_text_memcpy'
ghc-iserv-prof: /home/palmer/.cache/bazel/_bazel_palmer/9ef7fb33c244ac0b713bdee31c7518e3/execroot/work_project/bazel-out/k8-dbg/bin/external/haskell_text/libHSexternalZShaskellZUtextZStext_p.a: unknown symbol `externalZZShaskellZZUtextZZStext_DataziTextziArray_empty_closure'
ghc-iserv-prof: /home/palmer/.cache/bazel/_bazel_palmer/9ef7fb33c244ac0b713bdee31c7518e3/execroot/work_project/bazel-out/k8-dbg/bin/external/haskell_text/libHSexternalZShaskellZUtextZStext_p.a: unknown symbol `externalZZShaskellZZUtextZZStext_DataziTextziInternal_Text_con_info'
ghc-iserv-prof: /home/palmer/.cache/bazel/_bazel_palmer/9ef7fb33c244ac0b713bdee31c7518e3/execroot/work_project/bazel-out/k8-dbg/bin/external/haskell_text/libHSexternalZShaskellZUtextZStext_p.a: unknown symbol `externalZZShaskellZZUtextZZStext_DataziTextziUnsafe_iter_closure'
ghc-iserv-prof: /home/palmer/.cache/bazel/_bazel_palmer/9ef7fb33c244ac0b713bdee31c7518e3/execroot/work_project/bazel-out/k8-dbg/bin/external/haskell_parsec/libHSexternalZShaskellZUparsecZSparsec_p.a: unknown symbol `externalZZShaskellZZUtextZZStext_DataziText_uncons_closure'
ghc-iserv-prof: /home/palmer/.cache/bazel/_bazel_palmer/9ef7fb33c244ac0b713bdee31c7518e3/execroot/work_project/bazel-out/k8-dbg/bin/external/haskell_inline_c/libHSexternalZShaskellZUinlineZUcZSinline-c_p.a: unknown symbol `externalZZShaskellZZUparsecZZSparsec_TextziParsecziPrim_parse_closure'
ghc-iserv-prof: /home/palmer/.cache/bazel/_bazel_palmer/9ef7fb33c244ac0b713bdee31c7518e3/sandbox/linux-sandbox/2089/execroot/work_project/bazel-out/k8-dbg/bin/haskell/platform-policy-framework-vw/_obj_prof/platform-policy-framework-vw/Platform/Policy/Framework/VW/FFI/Context.p_o: unknown symbol `externalZZShaskellZZUinlineZZUcZZSinlinezmc_LanguageziCziTypesziParse_zdfShowCIdentifier_closure'
```

**Comment by guibou** [comment]
I'm sure that's related to #394 or #414

**Comment by mboes** [comment]
@guibou close?

**Comment by guibou** [comment]
@palmerlao have you tested this with more recent rules_haskell. Especially now that #394 is fixed?

**Comment by moritzkiefer-da** [comment]
Hey, I am seeing this in the `rules_haskell_examples` repo:

Steps to reproduce:
- Clone the rules_haskell_examples repo (current commit is `1db81dc6b89d54371387e4e7ad92236efe9db04d`)
- go to `cat_hs`
- run `bazel build -c dbg @haskell_text_show//:text-show`

Error:
```
ghc-iserv-prof: /home/moritz/.cache/bazel/_bazel_moritz/d72e5f08c2dd01966872541a48bb359d/execroot/cat_hs/bazel-out/k8-dbg/bin/external/haskell_text/libHSexternalZShaskellZUtextZStext_p.a: unknown symbol `_hs_text_memcpy'
ghc-iserv-prof: /home/moritz/.cache/bazel/_bazel_moritz/d72e5f08c2dd01966872541a48bb359d/execroot/cat_hs/bazel-out/k8-dbg/bin/external/haskell_text/libHSexternalZShaskellZUtextZStext_p.a: unknown symbol `externalZZShaskellZZUtextZZStext_DataziTextziArray_unsafeWrite_closure'
ghc-iserv-prof: /home/moritz/.cache/bazel/_bazel_moritz/d72e5f08c2dd01966872541a48bb359d/execroot/cat_hs/bazel-out/k8-dbg/bin/external/haskell_text/libHSexternalZShaskellZUtextZStext_p.a: unknown symbol `externalZZShaskellZZUtextZZStext_DataziTextziInternalziUnsafeziChar_unsafeWrite_closure'
ghc-iserv-prof: /home/moritz/.cache/bazel/_bazel_moritz/d72e5f08c2dd01966872541a48bb359d/sandbox/linux-sandbox/124/execroot/cat_hs/bazel-out/k8-dbg/bin/external/haskell_text_show/_obj_prof/text-show/TextShow/Classes.p_o: unknown symbol `externalZZShaskellZZUtextZZStext_DataziTextziInternalziBuilder_toLazzyText_closure'
```

I also tried bumping `RULES_HASKEL_VERSION` in `cat_hs/WORKSPACE` to the latest (`b24924dad34912326cb50d52afde685f93e2a776`) but that doesn’t seem to change anything.

**Comment by Profpatsch** [comment]
@moritzkiefer-da Can you still reproduce on a current `rules_haskell` (and `bazel`)?

**Comment by Profpatsch** [comment]
Ping.

**Comment by moritzkiefer-da** [comment]
Sorry for not responding earlier, I completely forgot about this issue. This issue seems to be fixed, thank you! (I can’t close the issue since I didn’t open it so I’ll leave that up to you).
